// @generated
// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Events {
    #[prost(message, optional, tag="1")]
    pub clock: ::core::option::Option<::substreams::pb::substreams::Clock>,
    #[prost(message, repeated, tag="2")]
    pub events: ::prost::alloc::vec::Vec<Event>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Event {
    #[prost(message, optional, tag="1")]
    pub log: ::core::option::Option<::substreams_aelf::pb::aelf::v1::LogEvent>,
    #[prost(string, tag="2")]
    pub tx_id: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StateUpdate {
    #[prost(string, tag="1")]
    pub tx_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub key: ::prost::alloc::string::String,
    #[prost(bytes="vec", tag="3")]
    pub value: ::prost::alloc::vec::Vec<u8>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StateUpdates {
    #[prost(message, optional, tag="1")]
    pub clock: ::core::option::Option<::substreams::pb::substreams::Clock>,
    #[prost(message, repeated, tag="2")]
    pub updates: ::prost::alloc::vec::Vec<StateUpdate>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Transactions {
    #[prost(message, optional, tag="1")]
    pub clock: ::core::option::Option<::substreams::pb::substreams::Clock>,
    #[prost(message, repeated, tag="2")]
    pub transactions: ::prost::alloc::vec::Vec<::substreams_aelf::pb::aelf::v1::TransactionTrace>,
}
// @@protoc_insertion_point(module)
